// flow-typed signature: 73aa3cc01cc27b51a0a3f78372db3719
// flow-typed version: <<STUB>>/eslint-config-wiremore_v^2.3.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-wiremore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-wiremore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-wiremore/postinstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-wiremore/index' {
  declare module.exports: $Exports<'eslint-config-wiremore'>;
}
declare module 'eslint-config-wiremore/index.js' {
  declare module.exports: $Exports<'eslint-config-wiremore'>;
}
declare module 'eslint-config-wiremore/postinstall.js' {
  declare module.exports: $Exports<'eslint-config-wiremore/postinstall'>;
}
