// flow-typed signature: 88d8bb29122fde9c286e76c732463dda
// flow-typed version: <<STUB>>/install-deps-postmerge_v^1.0.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'install-deps-postmerge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'install-deps-postmerge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'install-deps-postmerge/lib/defaults' {
  declare module.exports: any;
}

declare module 'install-deps-postmerge/lib/git' {
  declare module.exports: any;
}

declare module 'install-deps-postmerge/lib/install' {
  declare module.exports: any;
}

declare module 'install-deps-postmerge/lib/onError' {
  declare module.exports: any;
}

declare module 'install-deps-postmerge/scripts/markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'install-deps-postmerge/index' {
  declare module.exports: $Exports<'install-deps-postmerge'>;
}
declare module 'install-deps-postmerge/index.js' {
  declare module.exports: $Exports<'install-deps-postmerge'>;
}
declare module 'install-deps-postmerge/lib/defaults.js' {
  declare module.exports: $Exports<'install-deps-postmerge/lib/defaults'>;
}
declare module 'install-deps-postmerge/lib/git.js' {
  declare module.exports: $Exports<'install-deps-postmerge/lib/git'>;
}
declare module 'install-deps-postmerge/lib/install.js' {
  declare module.exports: $Exports<'install-deps-postmerge/lib/install'>;
}
declare module 'install-deps-postmerge/lib/onError.js' {
  declare module.exports: $Exports<'install-deps-postmerge/lib/onError'>;
}
declare module 'install-deps-postmerge/scripts/markdown.js' {
  declare module.exports: $Exports<'install-deps-postmerge/scripts/markdown'>;
}
