// flow-typed signature: 9ecf968724a0289363620e72f59409ba
// flow-typed version: <<STUB>>/plop-prettier_v^2.0.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plop-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plop-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plop-prettier/lib/index' {
  declare module.exports: any;
}

declare module 'plop-prettier/lib/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plop-prettier/lib/index.js' {
  declare module.exports: $Exports<'plop-prettier/lib/index'>;
}
declare module 'plop-prettier/lib/promisify.js' {
  declare module.exports: $Exports<'plop-prettier/lib/promisify'>;
}
