// flow-typed signature: e85019b36d049d59efb1935f81d21d2d
// flow-typed version: <<STUB>>/postcss-assets_v^5.0.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-assets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-assets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-assets/lib/__utils__/generateFileUniqueId' {
  declare module.exports: any;
}

declare module 'postcss-assets/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-assets/lib/quote' {
  declare module.exports: any;
}

declare module 'postcss-assets/lib/unescape-css' {
  declare module.exports: any;
}

declare module 'postcss-assets/lib/unquote' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-assets/lib/__utils__/generateFileUniqueId.js' {
  declare module.exports: $Exports<'postcss-assets/lib/__utils__/generateFileUniqueId'>;
}
declare module 'postcss-assets/lib/index.js' {
  declare module.exports: $Exports<'postcss-assets/lib/index'>;
}
declare module 'postcss-assets/lib/quote.js' {
  declare module.exports: $Exports<'postcss-assets/lib/quote'>;
}
declare module 'postcss-assets/lib/unescape-css.js' {
  declare module.exports: $Exports<'postcss-assets/lib/unescape-css'>;
}
declare module 'postcss-assets/lib/unquote.js' {
  declare module.exports: $Exports<'postcss-assets/lib/unquote'>;
}
