// flow-typed signature: f6eb5ce460167b4ae49a14a576e019b0
// flow-typed version: <<STUB>>/postcss-custom-properties_v^8.0.10/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-custom-properties/index' {
  declare module.exports: $Exports<'postcss-custom-properties'>;
}
declare module 'postcss-custom-properties/index.js' {
  declare module.exports: $Exports<'postcss-custom-properties'>;
}
